name: sujud
description: Bringing the Mosque to your Community
publish_to: 'none'
version: 0.0.1+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  amplify_api: ^1.6.2
  amplify_auth_cognito: ^1.6.2
  amplify_datastore: ^1.6.0
  amplify_flutter: ^1.6.1
  amplify_storage_s3: ^1.6.2
  app_settings: ^5.1.1
  async: ^2.11.0

  bloc_presentation: ^1.0.0

  cached_network_image: ^3.3.1
  cherry_toast: ^1.8.0
  collection: ^1.18.0
  connectivity_plus: ^5.0.2
  country_state_city: ^0.1.6
  cupertino_icons: ^1.0.6

  dio: ^5.4.0
  dropdown_search: ^5.0.6

  equatable: ^2.0.5
  expandable_page_view: ^1.0.17

  fl_country_code_picker: ^0.1.9+1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_dotenv: ^5.1.0
  flutter_form_builder: ^9.2.1
  flutter_localizations:
    sdk: flutter
  flutter_platform_widgets: ^6.0.2
  flutter_secure_storage: ^9.0.0
  form_builder_extra_fields: ^10.1.0
  form_builder_validators: ^9.1.0
  freezed_annotation: ^2.4.1

  get_it: ^7.6.7
  go_router: ^13.1.0
  google_fonts: ^6.1.0
  graphql: ^5.1.3
  graphql_flutter: ^5.1.2

  hijri: ^3.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hydrated_bloc: ^9.1.3

  image_picker: ^1.0.7
  in_app_review: ^2.0.8
  intl: ^0.18.1
  ionicons: ^0.2.2

  loading_animation_widget: ^1.2.0+4
  localstore: ^1.3.5
  logger: ^2.0.2+1

  page_transition: ^2.1.0
  page_view_indicators: ^2.0.0
  path: ^1.8.3
  path_provider: ^2.1.2
  phone_numbers_parser: ^8.1.2

  qr_flutter: ^4.1.0

  replay_bloc: ^0.2.5
  rxdart: ^0.27.7

  share_plus: ^7.2.2
  shared_preferences: ^2.2.2
  stack_trace: ^1.11.1
  step_progress_indicator: ^1.0.2

  unicons: ^2.1.1
  url_launcher: ^6.2.4
  url_strategy: ^0.2.0

dev_dependencies:
  build_runner: ^2.4.8
  build_verify: ^3.1.0

  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  freezed: ^2.4.6

  go_router_builder: ^2.4.1

  hive_generator: ^2.0.1
  http_mock_adapter: ^0.6.1

  import_sorter: ^4.6.0
  intl_translation: ^0.18.2

flutter:
  uses-material-design: true
  generate: false
  assets:
    - lib/assets/images/mosque.png
    - env.development
    - env.production
    - env.staging

import_sorter:
  emojis: true
  comments: true

analyzer:
  errors:
    invalid_annotation_target: ignore700